# Generated by Django 6.0 on 2025-12-06 10:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор заяки на выплату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('KZT', 'Казахстанский тенге'), ('CNY', 'Китайский юань')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('recipient_details', models.JSONField(help_text='Банковские реквизиты в формате JSON', verbose_name='Реквизиты получателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('approved', 'Одобрена'), ('paid', 'Выплачена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о заявке', null=True, verbose_name='Описание или комментарий')),
            ],
        ),
    ]
