# Generated by Django 6.0 on 2025-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payoutclaim_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('processed', 'Обработана'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
